UNIFI_USERNAME = 'admin'
UNIFI_PASSWORD = 'belastend2342'
UNIFI_SITE = 'default'
UNIFI_URL = 'https://localhost:8443'
EXPIRE = 67  # in minutes
USAGES = 35
CUPS_SERVER = 'localhost'
CUPS_PRINTER = 'HP'
BUTTON_PIN = 3  # Button pin
